[package]
name = "thunderbit"
version = "0.0.1"
edition = "2021"
authors = [ "Noxmore <n@noxmore.dev>" ]
description = "Discontinued project"
license = "MIT"
repository = "https://github.com/Noxmore/thunderbit"
documentation = "https://docs.rs/thunderbit"
readme = "readme.md"

[dependencies]
